x-mount-app-and-user-git-config: &mount-app-and-user-git-config
  volumes:
    - "./:/app"
    - "~/.gitconfig:/home/pygitops/.gitconfig" # allow script to commit as user

services:

  # a fully loaded development environment to test new code
  devbox: &devbox
    build:
      dockerfile: "./docker/devbox.dockerfile"
      context: "."
    image: "pygitops-devbox"
    volumes:
      - "./:/app"

  # Run the test & lint suite in a dedicated container
  test:
    <<: *devbox
    command: "docker/run_tests.sh --format-code"

  lock-requirements:
    <<: *devbox
    user: root
    entrypoint: "/bin/bash"
    command: "docker/lock_requirements.sh"

  # generate and serve the project documentation locally
  mkdocs: &mkdocs
    <<: *devbox
    entrypoint: "mkdocs"
    ports:
      - "8000:8000"
    command: [ "serve", "--dev-addr=0.0.0.0:8000" ]

  mike:
    <<: [ *mkdocs, *mount-app-and-user-git-config ]
    entrypoint: "mike"
