site_name: pygitops Documentation
repo_url: https://github.com/wayfair-incubator/pygitops/
repo_name: wayfair-incubator/pygitops
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
  - Usage Guide:
    - making-changes-on-feature-branch.md
  - Why pygitops?: why-pygitops.md
  - Development Guide: development-guide.md
  - Reference: api.md
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "restructured-text"
          rendering:
            heading_level: 3
            show_root_heading: True
            show_source: False
            show_root_full_path: False
extra_css:
  - css/mkdocstrings.css
