#!/usr/bin/env bash

set -e

# Uninstall all existing packages to start fresh
uv pip uninstall --system -r <(uv pip freeze --system) 2>/dev/null || true

# Install all requirements (main, test, and docs) to capture complete dependency tree
uv pip install --system -r requirements.txt -r requirements-test.txt -r requirements-docs.txt

# Generate lock file with all resolved dependencies
printf "# THIS IS AN AUTOGENERATED LOCKFILE. DO NOT EDIT MANUALLY.\n" > requirements.lock
uv pip freeze --system >> requirements.lock

echo "Rebuild containers to verify there are no conflicts."
