name: CI

# Triggers the workflow on push or pull request
# events, but only for the main branch
on: [push, pull_request]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docs
        run: docker-compose run --rm mkdocs build --strict

      # publish dev docs
      - name: Publish (dev)
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: docs-site
          path: site/

      # publish prod docs
      - name: Publish (prod)
        if: github.ref == 'refs/heads/main'
        uses: JamesIvers/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site

